### ISSUE TITLE
Replace fork me on GitHub banner

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#15]
@hougasian has suggested replacing the "fork me on GitHub" banner with https://github.com/tholman/github-corners. 

I think this is a nice idea however I'm concerned that it may not be obvious to people what it is as the banners have become synonymous with open source projects.

I am also not sure how it would work on mobile with the hamburger menu being in that corner.

If anyone wants to have a go at swapping it out and raising a PR with screenshots that would be great!

**Comment by felix-hack** [comment]
I can try it!
