### ISSUE TITLE
Add community link

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#19]
It would be good to link to the [Gitter community](https://gitter.im/opsdroid) from the menu and footer.

A little thought will have to be put into this as the menu is already very wide.

Resulted from opsdroid/opsdroid#317.

**Comment by sanjsanj** [comment]
@jacobtomlinson May I have a go at this PR please?  Are there any requirements you have beyond the info presented here?

**Comment by sanjsanj** [comment]
"Community" feels like a good label for this, in future it could link to a page where you list multiple community interaction points, but for now it could just link to your Gitter.

If you just went with the existing layout then it could look like this:

## 400px wide Mobile

- Nav

![400px](https://user-images.githubusercontent.com/4478671/33497081-85aee02a-d6c4-11e7-9fc3-9b52f7a3bf1d.png)

- Footer

![footer-400px](https://user-images.githubusercontent.com/4478671/33498374-02f16810-d6c9-11e7-9bb3-1516863c187b.png)

## 800px wide Tablet

- Nav

![800px](https://user-images.githubusercontent.com/4478671/33497082-85cb7d02-d6c4-11e7-87e8-deb7cbb22908.png)

- Footer

![footer-800px](https://user-images.githubusercontent.com/4478671/33498384-0b60fa2e-d6c9-11e7-9a49-96fcb28eb9a0.png)

## 1400px wide Desktop

- Nav

![1400px](https://user-images.githubusercontent.com/4478671/33497083-85ea7d9c-d6c4-11e7-856a-c3c5b1c6b211.png)

- Footer

![footer-1400px](https://user-images.githubusercontent.com/4478671/33498393-1365e522-d6c9-11e7-91cf-97bae08c7072.png)
