### ISSUE TITLE
Add list of parsers/matchers

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#21]
Similar to the list of connectors, databases and skills it would be great to have a list of the supported NLU parsers/matchers.

This is probably a little trickier to dynamically generate as the parsers are part of the core project and not GitHub repos. Perhaps they could be retrieved from the [documentation index](https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml#L13) and provide links to the docs pages for each one.

**Comment by FabioRosado** [comment]
Just realised that we now have the parsers/matchers on the page, so I'm closing this issue
