### ISSUE TITLE
Fix link to documentation

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#23]
Currently the documentation link in the header and footer goes to the latest docs, however it should go to the stable docs.

Latest docs is rebuilt whenever code is merged into the master branch of the opsdroid repository and therefore contains documentation on unreleased features. The stable documentation is only built when a release is done and therefore only contains the features available at the time of the most recent release.

http://readthedocs.org/projects/opsdroid/versions/

**Comment by marysalemme** [comment]
Hi Jacob, 
I can pick this up, if it's ok with you?

**Comment by jacobtomlinson** [comment]
Please go ahead!
