### ISSUE TITLE
Fix demo chat text wrapping on mobile

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#27]
Currently when viewing on mobile some of the chat lines in the demo chat window are too long and cause the text to wrap. This ends up looking odd.

![image](https://user-images.githubusercontent.com/1610850/35322712-200a463a-00e3-11e8-91a8-4ea641d6e77a.png)

Either the chat box needs to be taller on mobile or the text needs to be smaller.

**Comment by felix-hack** [comment]
Even if this issue is a bit older, I PRed a fix for that. #29
