### ISSUE TITLE
Fix documentation links

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#37]
Currently, the documentation links on the website point to https://opsdroid.readthedocs.io. 

Now that we have our own domain these should be updated to point to https://docs.opsdroid.dev .

https://github.com/opsdroid/opsdroid.github.io/search?q=%22opsdroid.readthedocs.io%22&unscoped_q=%22opsdroid.readthedocs.io%22

**Comment by danielacodes** [comment]
Hi @jacobtomlinson 

I would like to help out with that issue. I'm contributing for the first and just want to be sure to make it correctly :) 
Should I change the links only in that 3 files found here?

https://github.com/opsdroid/opsdroid.github.io/search?q=%22opsdroid.readthedocs.io%22&unscoped_q=%22opsdroid.readthedocs.io%22

**Comment by FabioRosado** [comment]
Hello @danielacodes, thank you so much for wanting to help out with this issue it would be amazing if you could work on it.

You care correct we need to change every link that points to `readthedocs.io`.

Also, if you are participating on the hacktoberfest, I'm not sure if PR's open before october count, so you can wait until the 1st of October to raise the PR. With this in mind, please let us know if you do get any trouble when working on this issue 😄 👍

**Comment by danielacodes** [comment]
No problem, I can wait until 1st of October 👌
You can let me know if PR's will be open earlier 😉
Cheers!

**Comment by danielacodes** [comment]
Hey @FabioRosado, I saw that grvkmrpandit already updated links https://github.com/opsdroid/opsdroid.github.io/pull/39 

Should I work on that too? I would like to avoid double-work in this case 😉

**Comment by jacobtomlinson** [comment]
Having a quick look at #39 there seems to be some issues with it. I will of course ask grvkmrpandit to address these, but you may also feel free to raise a PR to solve the same problem. 

For a task like this I am not worried about duplicating effort, it's probably more valuable to you and others to practice.

**Comment by oorjitchowdhary** [comment]
hey, can i work on this one?

**Comment by FabioRosado** [comment]
Hello @oorjitchowdhary we already have two people interested in contributing to this issue. I'd advise you to check the main opsdroid repo as we have a few issues that are good for first time contributors.

Thank you for showing interest in helping in the project 😄 👍

**Comment by ryanjanborja** [comment]
Is this still an issue?

**Comment by jacobtomlinson** [comment]
Fixed in #48
