### ISSUE TITLE
Update community links

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#38]
Our community is mainly over in Matrix these days rather than Gitter (there is a bridge so it doesn't matter too much).

It would be great to replace [all the links to Gitter](https://github.com/opsdroid/opsdroid.github.io/search?q=%22gitter.im%2Fopsdroid%22&unscoped_q=%22gitter.im%2Fopsdroid%22) on this site to point to the [Matrix room](https://riot.im/app/#/room/#opsdroid-general:matrix.org) instead.

**Comment by jacobtomlinson** [comment]
Also see opsdroid/opsdroid#1084

**Comment by alexmarginean16** [comment]
Hey, I think this issue was solved already cause I can't find any Gitter links anymore.

**Comment by FabioRosado** [comment]
Hello Alex, you are correct this issue has been fixed already but didn't close with the merge of the PR.

I will close this PR now, we have a few issues that are great for new contributors on the main opsdroid repository, feel free to have a look and let us know if you need any help
