### ISSUE TITLE
Make responsive

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#5]
Currently the site looks a bit odd on mobile. It is using a grid so I readjusts but it's too wide for a phone. 

The chat animation should probably be hidden on mobile and the layout needs tweaking so it looks good.

**Comment by baumannzone** [comment]
Hello, how can I help you? What do you need with the mobile "view"?

**Comment by AntonyFenton** [comment]
I can help you out think i know whats causing it

**Comment by jacobtomlinson** [comment]
@baumannzone I'm not sure I fully understand your question. 

If you open this website on mobile you will see that layout is not particularly mobile friendly. The widths needs correcting, the animation needs hiding or resizing and just general design changes to make it look good on mobile.

**Comment by baumannzone** [comment]
Ok, I see it now. Where can we talk? Find me in twitter `@baumannzone` and we talk about this. I believe I can fix this fast.
