### ISSUE TITLE
Add blog posts from medium

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/opsdroid.github.io#6]
In keeping with the idea of grabbing content from other places dynamically it would be great to include the posts from the [medium blog](https://medium.com/opsdroid).

This will need to be done in JavaScript and probably read from the RSS feed. 

It should show the latest few posts.

**Comment by pjbollinger** [comment]
I would like to work on this. I plan on grabbing the titles of the last 3 blog posts and put those to the right of the `Skills` block.
