### ISSUE TITLE
font family of "All your needs in one single framework." doesn't resembles with the page font-family

### ISSUE THREAD

**Issue by ritiksaxena124** [opsdroid/opsdroid.github.io#69]
### Actual View
![Screenshot (34)](https://user-images.githubusercontent.com/51539117/188816217-e9e5c527-e085-4be0-8d3a-880b32954145.png)
### Required View
![Screenshot (33)](https://user-images.githubusercontent.com/51539117/188816362-0b8590eb-a669-44f7-a82f-33f7051b22c0.png)

**Comment by jacobtomlinson** [comment]
Thanks @ritiksaxena124, do you have any interest in opening a PR to resolve this?

**Comment by ritiksaxena124** [comment]
@jacobtomlinson yes definitely I would love to.
