### ISSUE TITLE
Menu item is not visible on mobile

### ISSUE THREAD

**Issue by juanfernandes** [opsdroid/opsdroid.github.io#7]
I just noticed that on mobile (using DevTools) does not show the hamburger menu icon.

**Comment by jacobtomlinson** [comment]
Great thanks! This definitely needs resolving.

**Comment by sparkle-sparkle** [comment]
I can add the hamburger menu icon for you.

**Comment by jasonwilliams** [comment]
Has this been resolved?
seems fine for me

**Comment by jacobtomlinson** [comment]
Yeah closed in #9
